name: Auto reviewer
on:
  pull_request:
    types: [ opened, ready_for_review, reopened ]
jobs:
  auto-reviewer:
    name: Auto reviewer
    runs-on: ubuntu-latest
    steps:
      - name: Request review
        uses: necojackarc/auto-request-review@v0.7.0
        with:
          token: ${{ secrets.SAESSAK_GITHUB_TOKEN }}
          config: .github/reviewers/reviewers.yml